config/routes.rb
Rails.application.routes.draw do
  root 'songs#index'

  resources :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  def index
    @songs = Song.all 
  end

  def show
  end

  def new
    @song = Song.new
  end

  def create
    song = Song.new(song_params)

    if song.save
      redirect_to songs_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to song_path(@song)
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to root_path
  end

  private
    def set_song
      @song = Song.find(params[:id])
    end

    def song_params
      params.require(:song).permit(
        :title,
        :artist,
        :rank,
        :genre
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Top100</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/edit.html.erb
<h1>Add New Song</h1>

<%= form_for @song do |f|%>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :artist %>
    <%= f.text_field :artist %>

    <%= f.label :rank %>
    <%= f.text_field :rank %>

    <%= f.label :genre %>
    <%= f.text_field :genre %>

    <%= f.submit %>
<% end %>

app/views/songs/index.html.erb
<h1>Top 100 Songs That Will Make Your Pants Drop</h1>

<%= link_to 'New Song', new_song_path %>
<ul>
<% @songs.each do |song| %>
    <li>
        <%= link_to song.title, song_path(song) %>

    </li>


<% end %>
</ul>

app/views/songs/new.html.erb
<h1>Add New Song</h1>

<%= form_for @song do |f|%>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :artist %>
    <%= f.text_field :artist %>

    <%= f.label :rank %>
    <%= f.text_field :rank %>

    <%= f.label :genre %>
    <%= f.text_field :genre %>

    <%= f.submit %>
<% end %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>

<h3>The Artist of this song is: <%= @song.artist %></h3>

<h4>Genre: <%= @song.genre %></h4>
<h4>Rank: <%= @song.rank %></h4>

<%= link_to 'Edit Song', edit_song_path(@song) %>

<%= link_to 'Delete Song', song_path(@song), method: :delete %>